create table KNOWLEDGE (
     ID bigserial NOT NULL CHECK ( ID > 0 )
         CONSTRAINT PK_KNOWLEDGE PRIMARY KEY,
     TITLE varchar(512) NOT NULL,
     AUTHOR varchar(100) NOT NULL,
     DATE_MONTH varchar(50),
     VIEW_COUNT integer NOT NULL,
     LIKE_COUNT integer NOT NULL,
     LINK varchar(1024) NOT NULL
);

create index IX_KNOWLEDGE__AUTHOR ON KNOWLEDGE (AUTHOR);
create index IX_KNOWLEDGE__TITLE ON KNOWLEDGE (TITLE);
create index IX_KNOWLEDGE__VIEW_COUNT ON KNOWLEDGE (VIEW_COUNT);
create index IX_KNOWLEDGE__LIKE_COUNT ON KNOWLEDGE (LIKE_COUNT);
